version: "3.8"

volumes:
  api:

services:
  app:
    container_name: restmongoapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - api:/usr/src/app/
