openapi: 3.0.3
info:
  title: express-auth-asset
  description: |-
    The app just shop website can buy and sell, u have seller and buyer. 
    as admin u can do any and has responsibility create dev blogs
    as super user u can see dashboard and get analitycs what was trending on this app (this one will be hard)
    as seller u can sell some product and get all access same as user.
    as buyer u only can buy and add whishlist

    here my techstack of this app:
    - CRUD roles, user, product
    - AUTH for product list using JWT OAuth
    - Validation input using JOI
    - Unit Testing using jest
    - Documentation using swagger
    - Control Flow using github
    - Database using MongoDB
    - Containerization using docker
    - CI/CD using github actions
    - Docker image for this app using docker compose
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /user/register:
    post:
      tags:
        - User API
      summary: Register new user
      description: Register new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Success register new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
  /user/login:
    post:
      tags:
        - User API
      summary: Login user
      description: Login user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: Success login user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
  /user/logout:
    post:
      tags:
        - User API
      summary: Logout user
      description: Logout user
      responses:
        "200":
          description: Success logout user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
  /product:
    post:
      tags:
        - Product API
      summary: Create new product
      description: Register a new product by user that has login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Success create new product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
      security:
        - authUser: []
    get:
      tags:
        - Product API
      summary: Get all product
      description: Get all product
      responses:
        "200":
          description: Get all Product that registered in app return in array of object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductListResponse"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
  /product/:id:
    get:
      tags:
        - Product API
      summary: Get product by Id
      description: Return one product detailed
      parameters:
        - name: id
          in: path
          description: Product Id
          required: true
          style: simple
          explode: false
          schema:
            type: number
      responses:
        "200":
          description: Success get product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
    put:
      tags:
        - Product API
      summary: Update product by Id
      description: Update product by Id, need authorize the user
      parameters:
        - name: id
          in: path
          description: Product Id
          required: true
          style: simple
          explode: false
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Success update product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
      security:
        - authUser: []
    delete:
      tags:
        - Product API
      summary: Delete product by Id
      description: Delete product by Id, need authorized access
      parameters:
        - name: id
          in: path
          description: Product Id
          required: true
          style: simple
          explode: false
          schema:
            type: number
      responses:
        "200":
          description: Success delete product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
      security:
        - authUser: []
  /productList:
    get:
      tags:
        - ProductList API
      summary: Get all product List for current user
      description: Get all product
      responses:
        "200":
          description: Success get all product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductListResponse"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
      security:
        - authUser: []
    delete:
      tags:
        - ProductList API
      summary: Delete all product List for current user
      description: Get all product
      responses:
        "200":
          description: Success get all product
      security:
        - authUser: []
  /productList/:id:
    post:
      tags:
        - ProductList API
      summary: Add Product to ProductList Owner
      description: "Add a role"
      parameters: []
      responses:
        "200":
          description: Adding Role
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductList"
        default:
          description: Error responses code other than 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
      security:
        - authUser: []
    delete:
      tags:
        - ProductList API
      summary: Delete product list by Id for current user
      description: Delete product by Id
      parameters:
        - name: id
          in: path
          description: Product Id
          required: true
          style: simple
          explode: false
          schema:
            type: number
      responses:
        "200":
          description: Success delete product
      security:
        - authUser: []
  /payments:
    post:
      tags:
        - Payments
      summary: Add payment invoice
      description: add payment for productlist
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductList"
      responses:
        "200":
          description: Success payment
      security:
        - authUser: []
    get:
      tags:
        - Payments
      summary: Get Log all Payments
      description: Get status Payment user with Id
      responses:
        "200":
          description: Success get status payment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LogPayment"
      security:
        - authUser: []
  /payments/:id:
    get:
      tags:
        - Payments
      summary: Get Status Payments
      description: Get status Payment user with Id
      responses:
        "200":
          description: Success get status payment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Default"
      security:
        - authUser: []
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        price:
          type: number
        status:
          type: boolean
        image:
          type: string
    User:
      type: object
      properties:
        id:
          type: number
        usernames:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    ProductList:
      description: Product list work like chart, user create chart the all the cart woll go payed
      type: object
      properties:
        id:
          type: string
        owner:
          $ref: "#/components/schemas/User"
        productList:
          type: array
          items:
            $ref: "#/components/schemas/Product"
    LogPayment:
      type: object
      properties:
        id:
          type: string
        trasactionId:
          type: string
        itemDetails:
          $ref: "#/components/schemas/ProductList"
        owner:
          $ref: "#/components/schemas/User"
        amount:
          type: integer
        createdAt:
          type: string
    Default:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        message:
          type: string
    ProductListResponse:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/ProductList"
    ProductResponse:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        data:
          $ref: "#/components/schemas/Product"

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              status:
                type: string
              message:
                type: string
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              status:
                type: string
              message:
                type: string
    NotFoundException:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              status:
                type: string
              message:
                type: string
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
              status:
                type: string
              message:
                type: string
  securitySchemes:
    authUser:
      type: http
      scheme: bearer
      bearerFormat: JWT
